# Generated by Django 3.2.7 on 2021-09-23 16:48

import app.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=stdimage.models.StdImageField(upload_to=app.models.get_file_path, verbose_name='Image'),
        ),
    ]
